### PR TITLE
Resolve conflicts on the last PR

### PR DESCRIPTION
**Pull request by ggoldens**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>Resolve conflicts on the last PR

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/105" target="_blank">ReviewNinja

**Comment by ggoldens** [comment]
👍

**Comment by ggoldens** [comment]
👍

**Comment by Lucashuang0802** [comment]
👍

**Pull request merged**
