### PR TITLE
Add the ability to set the gap between toolbar and color toolbar

### PR DESCRIPTION
**Pull request by aradiquez**
ability to set the float value between toolbar and color toolbar

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/46" target="_blank">ReviewNinja

**Comment by albertoacn** [comment]
Can one of the admins verify this patch?

**Comment by Lucashuang0802** [comment]
Let's expose the whole color picker bar instead of just the ability to change the height. As it needs deployment, let's hold it for now to see whether it has different approach to modify the gap from app level.

**Comment by Lucashuang0802** [comment]
Close it as I have removed the gap from the accelerator pack level. For sure, it's a global influence now. 😃

**Pull request closed without merging**
