### PR TITLE
Move platform data from type string to the body

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts. Confirmation: @Lucashuang0802

## What's in this pull request?

> Move platform data from type string to the body

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/90" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
👍

**Comment by adrice727** [comment]
LGTM

**Comment by Lucashuang0802** [comment]
👍

**Pull request merged**
