### PR TITLE
Updating version in the docs

### PR DESCRIPTION
**Pull request by marinaserranomontes**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/86" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
👍

**Comment by Lucashuang0802** [comment]
LGTM

**Comment by marinaserranomontes** [comment]
👍

**Pull request merged**
