### PR TITLE
Remove remote text-annotations

### PR DESCRIPTION
**Pull request by marinaserranomontes**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/107" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
#108

**Comment by Lucashuang0802** [comment]
it works good, there are two points to notice:
- it's not too necessary to create a new method `removeRemoteTextAnnotatable` 
- `[NSNull null]` is an universal obejct to indicate nullability which don't use it often. I transfer to use `nil` instead.

**Comment by Lucashuang0802** [comment]
Keep track on #108

**Pull request closed without merging**
