### PR TITLE
OTS-337 - AnnotationAccPack - open API to paint and erase to third pa…

### PR DESCRIPTION
**Pull request by crdlc**
…rties

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/60" target="_blank">ReviewNinja

**Comment by crdlc** [comment]
@marinaserranomontes Hi Marina, we need to hide the toolbar UI because of Tata design and to allow users to paint and clear from Tata's toolbar. Then we decided to open those features by means of events. Could you review this? Thanks in advance

**Comment by albertoacn** [comment]
Can one of the admins verify this patch?

**Comment by marinaserranomontes** [comment]
LGTM

**Comment by Lucashuang0802** [comment]
#60

**Comment by marinaserranomontes** [comment]
PLEASE, DO NOT MERGE YET

**Pull request closed without merging**
