### PR TITLE
OTS-337 - expose paint and erase API to public

### PR DESCRIPTION
**Pull request by crdlc**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/61" target="_blank">ReviewNinja

**Comment by albertoacn** [comment]
Can one of the admins verify this patch?

**Comment by adrice727** [comment]
@crdlc Can you make these changes to the `src` file?

**Comment by crdlc** [comment]
@adrice727, already done in src, thanks a lot

**Comment by adrice727** [comment]
@crdlc I'm not entirely sure what this change does.  Can you explain?

**Comment by crdlc** [comment]
It exposes two events to implement the same functionality than pencil and cross icons provide in the toolbar. We need this because both features are implemented in other place and the toolbar is hidden by Tata design

**Comment by marinaserranomontes** [comment]
PLEASE, DO NOT MERGE YET

**Comment by adrice727** [comment]
@crdlc There have been some changes to `annotation-widget.js` and there are now conflicts.  You can either merge `develop` into your branch and then push the changes so I can merge it, or I can add the changes as a separate commit and close the PR.  Just let me know.

**Comment by crdlc** [comment]
@adrice727 rebased develop, thanks

**Pull request merged**
