### PR TITLE
Creating android unit test suite

### PR DESCRIPTION
**Pull request by albertoacn**
@marinaserranomontes please merge :)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/38" target="_blank">ReviewNinja

**Comment by albertoacn** [comment]
Can one of the admins verify this patch?

**Comment by Lucashuang0802** [comment]
👍 please update the branch. @marinaserranomontes, please take a look. 😃

**Comment by marinaserranomontes** [comment]
New PR: https://github.com/opentok/annotation-acc-pack/pull/67

**Pull request closed without merging**
