### PR TITLE
Update logging entries

### PR DESCRIPTION
**Pull request by aradiquez**
removing spaces in action items for logger

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/39" target="_blank">ReviewNinja

**Comment by albertoacn** [comment]
Can one of the admins verify this patch?

**Comment by Lucashuang0802** [comment]
👍 please update the branch.

**Comment by marinaserranomontes** [comment]
@aradiquez  it seems to be out of date, please, could you review it? I think you need to update your branch with the last develop changes to fix the conflicts. Thanks!!

**Pull request merged**
