### PR TITLE
OTS-335 Make the image resources hosteable by the partner

### PR DESCRIPTION
**Pull request by AntonioMA**
r? @adrice727 @marinaserranomontes  or whomever :)
https://tokbox.atlassian.net/browse/OTS-335

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/annotation-acc-pack/pull/57" target="_blank">ReviewNinja

**Comment by albertoacn** [comment]
Can one of the admins verify this patch?

**Comment by adrice727** [comment]
@AntonioMA Can you replace `const` with `var` in `annotation-widget.js`?

**Comment by AntonioMA** [comment]
Done and updated

**Comment by Lucashuang0802** [comment]
thx @AntonioMA. BTW, iOS is expected to fail. @adrice727.

**Pull request merged**
